### ISSUE TITLE
PaymentType lost 'SUBSCRIPTION' value

### ISSUE THREAD

**Issue by altro3** [checkout/checkout-sdk-java#32] opened 2020-12-02 13:26 UTC
Sample webhook:
```json
{
    "id": "evt_vzpfnvvbqfmefpjlns5znj2opu",
    "type": "payment_approved",
    "created_on": "2020-12-02T10:54:57Z",
    "data": {
        "action_id": "act_4h6yqwomkzmezn7qbpbden6kvm",
        "payment_type": "SUBSCRIPTION",
        "auth_code": "739301",
        "response_code": "10000",
        "response_summary": "Approved",
        "scheme_id": "100742343895990",
        "3ds": {
            "downgraded": false,
            "enrolled": "Y",
            "signature_valid": "Y",
            "authentication_response": "Y",
            "eci": "02",
            "cavv": "hv8mUFzPzRZoCAAAAAEQBDMAAAA=",
            "xid": "MDAwMDAwMDAwMDAwMDAwMzIyNzY="
        },
        "source": {
            "id": "src_x633r7e6ox6ephctmtgrah65jm",
            "type": "card",
            "billing_address": {},
            "expiry_month": 5,
            "expiry_year": 2030,
            "name": "test name",
            "scheme": "MASTERCARD",
            "last_4": "3404",
            "fingerprint": "e3d8eed03133dc7a3be8f1b446596ae99bdcf67a4d1bd4c56285182d00e1a0eb",
            "bin": "535215",
            "card_type": "Debit",
            "card_category": "Commercial",
            "issuer": "JSB PIVDENNYI",
            "issuer_country": "UA",
            "product_id": "MDT",
            "product_type": "Commercial Debit MasterCard® Card",
            "avs_check": "S",
            "cvv_check": "Y"
        },
        "customer": {
            "id": "cus_dhfgh2pngviudjou5daemmdmx4",
            "email": "user@emailweweweew.com"
        },
        "processing": {
            "acquirer_transaction_id": "3300105946",
            "retrieval_reference_number": "499966563601"
        },
        "amount": 23999,
        "metadata": {
            "userId": "143820"
        },
        "risk": {
            "flagged": false
        },
        "id": "pay_4h6yqwomkzmezn7qbpbden6kvm",
        "currency": "USD",
        "processed_on": "2020-12-02T10:54:57Z",
        "reference": "9462"
    },
    "_links": {
        "self": {
            "href": "https://api.sandbox.checkout.com/events/evt_vzpfnvvbqfmefpjlns5znj2opu"
        },
        "payment": {
            "href": "https://api.sandbox.checkout.com/payments/pay_4h6yqwomkzmezn7qbpbden6kvm"
        }
    }
}
```
As you see, in field `payment_type` value "SUBSCRIPTION",

Class `com.checkout.payments.PaymentType` hasn't this value.

**Comment by harry-peirse** [comment] 2021-02-21 16:32
Hi, sorry for not seeing this for a couple of months!

@nicolas-maalouf-cko correct me if I'm wrong, but looking at https://api-reference.checkout.com/#operation/requestAPaymentOrPayout the valid values here don't include SUBSCRIPTION. This is the list the PaymentType constants are based on in the SDK.

We don't have first class support for deserializing webhooks in the SDK today, so @altro3 I suggest you stick with a string comparison rather than using this constants for this. Though it's interesting to know you are using the SDK with your Webhooks - we hadn't fully considered that situation I believe.

**Comment by harry-peirse** [comment] 2021-02-21 16:33
I'll tag this as wontfix for the moment, but maybe we can revisit better Webhook support in a subsequent release.

**Comment by rsaestrela** [comment] 2021-08-18 08:44
Closing this issue because it has been inactive for a few months and it is not reproducible or it has been fixed in a newer version.

**Closed by rsaestrela** 2021-08-18 08:44 UTC
Labels: wontfix
